import generate_time_table
import op_crm_employee_performance_analysis
import op_crm_lead_analysis
import op_enrollment_analysis
import op_promotional_activity_analysis
import op_followup_actions_detail_analysis
import op_inquiry_modes_analysis